# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=100)),
                ('user_birthday', models.DateField(null=True)),
                ('user_comment', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pd', 'pending'), ('rj', 'rejected'), ('cp', 'complete')], default='pd', max_length=2)),
                ('confirm_file', models.CharField(max_length=255)),
            ],
        ),
    ]
