# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_order', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm_file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_full_name',
            field=models.CharField(max_length=100),
        ),
    ]
