# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_order', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pd', '\u0432 \u043e\u0436\u0438\u0434\u0430\u043d\u043d\u0438\u0438'), ('rj', '\u043e\u0442\u043a\u043b\u043e\u043d\u0435\u043d'), ('cp', '\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default='pd', max_length=2),
        ),
    ]
