# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_order', '0003_auto_20230604_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'complete')], default='0', max_length=2),
        ),
    ]
