# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_order', '0004_auto_20230604_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
