# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_order', '0005_auto_20230604_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pd', 'pending'), ('rj', 'rejected'), ('cp', 'complete')], default='pd', max_length=2),
        ),
    ]
